version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: |
            mkdir junit
            npm test -- --reporter mocha-junit-reporter

          environment:
            MOCHA_FILE: junit/test-results.xml

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit
  build-react-16:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - run:
          name: change-package.json
          command: mv package.json package15.json

      - run:
          name: change-package.json-2
          command: cp package16.json package.json

      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: |
            mkdir junit
            npm test -- --reporter mocha-junit-reporter

          environment:
            MOCHA_FILE: junit/test-results.xml

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

      - run:
          name: change-package.json-2
          command: cp package15.json package.json
  update-gh-pages:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build-gh-pages
          command: ./scripts/gh-pages/build.sh

      - run:
          name: deploy-gh-pages
          command: ./scripts/gh-pages/deploy.sh .gh-pages-tmp

workflows:
  version: 2
  build-all:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - update-gh-pages:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
